### ISSUE TITLE
Setup an IRC channel

### ISSUE THREAD

**Issue by ghost** [nairuby/nairuby.org#15]
It would be very welcome to set up an IRC (internet relay chat) channel. IRC is a great way for people who don’t otherwise know each other to meet and interact. I will suggest setting it up at Freenode 

Freenode is an IRC server with a very specific mission: “to provide discussion facilities for the Free and Open Source Software communities, for not-for-profit organizations and for related communities and organizations”. It is a very friendly place and active moderators keep it comfortable and inviting. 

"It is a great place for people new to a technology to learn the ropes, meet like-minded professionals, and help others."

**Comment by bkmgit** [comment]
Good suggestion, consider re-opening. Possibly need a bridge to other similar options.
