### ISSUE TITLE
Add entry on rubyusergroups.org

### ISSUE THREAD

**Issue by itskingori** [nairuby/nairuby.org#18]
@georgeG There's a listing of Ruby user groups around the world at [rubyusergroups.org](http://rubyusergroups.org/) with an entry "Nairobi Ruby Users Group" in Kenya. Seems like you were the one who set it up as it links to a [rubyforge account](http://rubyforge.org/projects/nairobi/) set up by you back in 2007.

Any ideas? If you are the one, you can update it (if it requires login, not too sure) ... if not there's a message at the top of the page which says;

>  If we've got your group details wrong, please berate us at info@rubyusergroups.org

**Comment by bkmgit** [comment]
Site update functionality seems broken. Cannot update at present.
