### ISSUE TITLE
Create the remaining social media pages

### ISSUE THREAD

**Issue by Banta** [nairuby/nairuby.org#21]
That is;
- [x] Google+
- [x] Facebook
- [x] Linkedin

... and link all to nairuby.org

**Comment by itsmrwave** [comment]
G+ and FB added here bc61781858351d818ff4682bd5e7001bd9cb14c1 by @Banta ... LinkedIn left (if it's still in the plan).

**Comment by iamleader** [comment]
Reviewing this and noted now we have Meetup and Slack. Creating LinkedIn COB today, most of our sponsors  and members are on LinkedIn.

**Comment by itsmrwave** [comment]
We have Slack?

How do I jump in?:-)

— King'ori Maina (kingori.co)

**Comment by iamleader** [comment]
Just added you using j@kingori.co confirm receipt.

**Comment by itsmrwave** [comment]
@iamleader :+1: ... edited my email out of you comment though :-) ... don't want the spam bots picking it up.

**Comment by iamleader** [comment]
@itsmrwave  :+1: Done :)

**Comment by iamleader** [comment]
https://www.linkedin.com/company/nairuby

**Comment by iamleader** [comment]
I am not sure if this is the thread I should post this but we should now consider adding LinkedIn (https://www.linkedin.com/company/nairuby) and Meetup (http://www.meetup.com/Nairuby/)  page on nairuby.org. They will serve different purpose going forward.

**Comment by itsmrwave** [comment]
@iamleader Oh, pole. I think I closed this thinking the issue was about creating the pages not adding them to the page. So yes, I agree with you. Will add them.

**Comment by iamleader** [comment]
No worries.

**Comment by bkmgit** [comment]
Relevant profiles seem to have been added. Better to create new issues for new profiles.
